CREATE TABLE mytable(
   "Event title"  VARCHAR(44) NOT NULL PRIMARY KEY
  ,"Photo link"   VARCHAR(82) NOT NULL
  ,Day            VARCHAR(9)
  ,Date           DATE  NOT NULL
  ,Time           VARCHAR(8)
  ,Recurring      VARCHAR(5) NOT NULL
  ,"Active event" VARCHAR(5) NOT NULL
  ,Place          VARCHAR(25)
  ,Building       VARCHAR(15)
  ,Organizer      VARCHAR(45) NOT NULL
  ,"Misc tags"    VARCHAR(27)
);
INSERT INTO mytable("Event title","Photo link",Day,Date,Time,Recurring,"Active event",Place,Building,Organizer,"Misc tags") VALUES ('Student and faculty mixer','https://drive.google.com/file/d/1gs1eDOuCeSR8zc-yEyIVMSEDxvqmbtEu/view?usp=sharing','Monday','02/24/2025','5:30 PM','FALSE','TRUE','Center of DEI','CUC','CMU Colorstack','Academic');
INSERT INTO mytable("Event title","Photo link",Day,Date,Time,Recurring,"Active event",Place,Building,Organizer,"Misc tags") VALUES ('Datathon','https://drive.google.com/file/d/1fvVwhyTU3vFEL7N8QyVUQSF24MottRwJ/view?usp=sharing',NULL,'03/29/2025','9:00 AM','FALSE','TRUE',NULL,NULL,'MSCF Quant Leadership Alliance, CMU Math Club','Quant, Academic');
INSERT INTO mytable("Event title","Photo link",Day,Date,Time,Recurring,"Active event",Place,Building,Organizer,"Misc tags") VALUES ('Spring Break Trips','https://drive.google.com/file/d/1a15YyTFZ5zktdh3dDjRTNCrIHkIeSRvb/view?usp=sharing',NULL,'02/06/2025',NULL,'FALSE','FALSE',NULL,NULL,'Habitat for Humanity',NULL);
INSERT INTO mytable("Event title","Photo link",Day,Date,Time,Recurring,"Active event",Place,Building,Organizer,"Misc tags") VALUES ('Paws to Relax','https://drive.google.com/file/d/183phWWASlCebFsuosbdcj1y2mvHmFztt/view?usp=sharing','Monday','02/10/2025','7:00 PM','FALSE','TRUE','Well-being Lab (Room 104)','Highmark Center','Wellness & Meaning-Making Programs',NULL);
INSERT INTO mytable("Event title","Photo link",Day,Date,Time,Recurring,"Active event",Place,Building,Organizer,"Misc tags") VALUES ('Loving Kindness Week','https://drive.google.com/file/d/1GxAFK0ndvZqu-6zXWvtDItEYqRmNNBYC/view?usp=sharing','Sunday','02/09/2025','8:30 AM','TRUE','TRUE','Well-being Lab (Room 104)','Highmark Center','Wellness & Meaning-Making Programs',NULL);
INSERT INTO mytable("Event title","Photo link",Day,Date,Time,Recurring,"Active event",Place,Building,Organizer,"Misc tags") VALUES ('February Foot Soak','https://drive.google.com/file/d/1zpu4VgKoHacbGYJ2icuMYNAJKXX93pFV/view?usp=sharing','Tuesday','02/11/2025','5:00 PM','FALSE','TRUE','Well-being Lab (Room 104)','Highmark Center','Wellness & Meaning-Making Programs',NULL);
INSERT INTO mytable("Event title","Photo link",Day,Date,Time,Recurring,"Active event",Place,Building,Organizer,"Misc tags") VALUES ('Moving Forward Through Disagreements','https://drive.google.com/file/d/1iY_taHgcnthzeEjVCf4XvXHTUd0M_DIE/view?usp=sharing','Wednesday','02/13/2025','5:00 PM','FALSE','TRUE','Well-being Lab (Room 104)','Highmark Center','Wellness & Meaning-Making Programs',NULL);
INSERT INTO mytable("Event title","Photo link",Day,Date,Time,Recurring,"Active event",Place,Building,Organizer,"Misc tags") VALUES ('The Autonomous Body Shop','https://drive.google.com/file/d/19FtrkNMeow5bLveubrQMKJI1jQMdXRjH/view?usp=sharing','Wednesday','02/12/2025','12:00 PM','FALSE','TRUE','Merson Courtyard',NULL,'Autonomous Body Shop Student Ambassadors',NULL);
INSERT INTO mytable("Event title","Photo link",Day,Date,Time,Recurring,"Active event",Place,Building,Organizer,"Misc tags") VALUES ('Taalam','https://drive.google.com/file/d/1E1QS0kJ7-Jmb2JOmT4di4KQ7zRnF9Muk/view?usp=sharing','Saturday','02/15/2025','7:30 PM','FALSE','TRUE','Studio Theater','CUC','CMU Abhinaya','Dance');
INSERT INTO mytable("Event title","Photo link",Day,Date,Time,Recurring,"Active event",Place,Building,Organizer,"Misc tags") VALUES ('Pathways to Impact Careers in Sustainablilty','https://drive.google.com/file/d/14zbQLcd8j9HMxjPusNc70wbCQx0CV03e/view?usp=sharing','Sunday','02/16/2006','11:00 AM','FALSE','TRUE','PNC Rooms','Tepper','Sustainability Initiative','Sustainability, Environment');
INSERT INTO mytable("Event title","Photo link",Day,Date,Time,Recurring,"Active event",Place,Building,Organizer,"Misc tags") VALUES ('Laughter Yoga','https://drive.google.com/file/d/1-l4ujhn2G6FJQBz_GL08mZHwpkSQj9Re/view?usp=sharing','Thursday','02/20/2025','5:00 PM','FALSE','TRUE','Well-being Lab (Room 104)','Highmark Center','Wellness & Meaning-Making Programs','Yoga, Sport');
INSERT INTO mytable("Event title","Photo link",Day,Date,Time,Recurring,"Active event",Place,Building,Organizer,"Misc tags") VALUES ('Heartfulness Weekend Retreat','https://drive.google.com/file/d/1StA8ULJSoX7o_2CudZpAyPTSMuhlvhOF/view?usp=sharing','Friday','02/21/2025','5:00 PM','FALSE','TRUE','Well-being Lab (Room 104)','Highmark Center','Heartfulness','Yoga, Sport');
INSERT INTO mytable("Event title","Photo link",Day,Date,Time,Recurring,"Active event",Place,Building,Organizer,"Misc tags") VALUES ('Pittsburgh Alternative Break','https://drive.google.com/file/d/1KG__sjhe1TCvXn688T85gQjk98szAwC_/view?usp=sharing','Monday','03/03/2025',NULL,'FALSE','TRUE','Pittsburgh',NULL,'SLICE','Spring break');
INSERT INTO mytable("Event title","Photo link",Day,Date,Time,Recurring,"Active event",Place,Building,Organizer,"Misc tags") VALUES ('Heartfulness Through Meditation','https://drive.google.com/file/d/1za0IwygrUccxCZ4Byq8o3CLnLi4AnFp8/view?usp=sharing','Sunday','02/08/2025','8:30 AM','TRUE','TRUE','Well-being Lab (Room 104)','Highmark Center','Heartfulness','Yoga, Sport');
INSERT INTO mytable("Event title","Photo link",Day,Date,Time,Recurring,"Active event",Place,Building,Organizer,"Misc tags") VALUES ('Sky Meditation Hour','https://drive.google.com/file/d/1mxCMCUzc5q1jRnXqJCzsBlKbFfZGyDH9/view?usp=sharing','Monday','02/10/2025','5:00 PM','TRUE','TRUE','Well-being Lab (Room 104)','Highmark Center','Wellness & Meaning-Making Programs','Yoga, Sport');
INSERT INTO mytable("Event title","Photo link",Day,Date,Time,Recurring,"Active event",Place,Building,Organizer,"Misc tags") VALUES ('Drop In Hours','https://drive.google.com/file/d/1OEjeRDIIGkclYmkz_vTHJ2amagUX2pPD/view?usp=sharing','Tuesday','02/11/2025','5:00 PM','TRUE','TRUE','Highmark Lobby','Highmark Center','Peer Health Advocated',NULL);
INSERT INTO mytable("Event title","Photo link",Day,Date,Time,Recurring,"Active event",Place,Building,Organizer,"Misc tags") VALUES ('Paws to Relax Pet Therapy','https://drive.google.com/file/d/1mNLBoKJ6sXyGoo3vkrn3YpnmwxPpsOyp/view?usp=sharing','Wednesday','02/12/2025','7:00 PM','TRUE','TRUE','Well-being Lab (Room 104)','Highmark Center','Wellness & Meaning-Making Programs',NULL);
INSERT INTO mytable("Event title","Photo link",Day,Date,Time,Recurring,"Active event",Place,Building,Organizer,"Misc tags") VALUES ('Discover Tranquility','https://drive.google.com/file/d/16Xy5sAV_LRpkrMnkwStpEHzfKlB4-06w/view?usp=sharing','Wednesday','02/12/2025','1:00 PM','TRUE','TRUE','Well-being Lab (Room 104)','Highmark Center','Sky Campus Happiness','Yoga, Sport');
INSERT INTO mytable("Event title","Photo link",Day,Date,Time,Recurring,"Active event",Place,Building,Organizer,"Misc tags") VALUES ('Monthly Crafternoon','https://drive.google.com/file/d/1apFej_h6hzdlv_GwIgxu7GiBNs2itjle/view?usp=sharing','Thursday','02/20/2025','11:00 AM','TRUE','TRUE','Well-being Lab (Room 104)','Highmark Center','Wellness & Meaning-Making Programs',NULL);
INSERT INTO mytable("Event title","Photo link",Day,Date,Time,Recurring,"Active event",Place,Building,Organizer,"Misc tags") VALUES ('The Sangha','https://drive.google.com/file/d/1XEgSxdBmmrmmCgpM5CZ6A6I6GTkto6Wq/view?usp=sharing','Tuesday','02/25/2025','5:00 PM','TRUE','TRUE','Well-being Lab (Room 104)','Highmark Center','Wellness & Meaning-Making Programs',NULL);
INSERT INTO mytable("Event title","Photo link",Day,Date,Time,Recurring,"Active event",Place,Building,Organizer,"Misc tags") VALUES ('Virtual Gratitude Gathering','https://drive.google.com/file/d/1yun-TSSMxLt_3jw8tRwAQlexViruU39h/view?usp=sharing','Tuesdays','02/25/2025','12:00 PM','TRUE','TRUE','Well-being Lab (Room 104)','Highmark Center','Wellness & Meaning-Making Programs',NULL);
INSERT INTO mytable("Event title","Photo link",Day,Date,Time,Recurring,"Active event",Place,Building,Organizer,"Misc tags") VALUES ('Women''s Club BBall Practice','https://drive.google.com/file/d/1aNtpigaa1A-DNgyaKYjm3CiTphlqOdnO/view?usp=sharing','Thursday','02/13/2025','7:00 PM','TRUE','TRUE','Highmark Gym','Highmark Center','Women''s Club Basketball','Sport');
INSERT INTO mytable("Event title","Photo link",Day,Date,Time,Recurring,"Active event",Place,Building,Organizer,"Misc tags") VALUES ('Rise Against Hunger','https://drive.google.com/file/d/18re7Phba1vFkZ1dkqo-AabJcaK9c5jii/view?usp=sharing','Saturday','02/15/2025','10:30 AM','TRUE','TRUE','Wiegand Gym','CUC','SLICE',NULL);
INSERT INTO mytable("Event title","Photo link",Day,Date,Time,Recurring,"Active event",Place,Building,Organizer,"Misc tags") VALUES ('WiCys','https://drive.google.com/file/d/1KlLUyvAQa7Ch5UDgAyy9Rpa0Hh0lw4IX/view?usp=sharing','Wednesday','02/12/2025','5:00 PM','TRUE','TRUE','HBH 2003','Hamburg Hall','Women in CyberSecurity',NULL);
INSERT INTO mytable("Event title","Photo link",Day,Date,Time,Recurring,"Active event",Place,Building,Organizer,"Misc tags") VALUES ('Lightsaber Training','https://drive.google.com/file/d/1VklT_sw3j9rLnXfG_EyOm9Ilvk6rOhAV/view?usp=sharing','Sunday','02/09/2025','5:00 PM','TRUE','TRUE','Racquetball Court A',NULL,'CMU Star Wars',NULL);
INSERT INTO mytable("Event title","Photo link",Day,Date,Time,Recurring,"Active event",Place,Building,Organizer,"Misc tags") VALUES ('Meditation Hour','https://drive.google.com/file/d/1SWy8l3eSbtjf6w5IoX-8cmaE9igJ06TH/view?usp=sharing','Monday','02/10/2025','5:00 PM','TRUE','TRUE','Well-being Lab (Room 104)','Highmark Center','Sky Campus Happiness',NULL);
